data2bag_kitti:
  ros__parameters:
    data_path: "/home/myx/develop/data/test_data"

    point_cloud_topic_name: "/kitti/point_cloud"
    image_gray_left_topic_name: "/kitti/image/gray/left"
    image_gray_right_topic_name: "/kitti/image/gray/right"
    image_color_left_topic_name: "/kitti/image/color/left"
    image_color_right_topic_name: "/kitti/image/color/right"
    imu_topic_name: "/kitti/imu"
    nav_sat_fix_topic_name: "/kitti/nav_sat_fix"
    marker_arr_topic_name: "/kitti/marker_array"

    point_cloud_frame_id: "velodyne"
    image_gray_left_frame_id: "gray_camera_left"
    image_gray_right_frame_id: "gray_camera_right"
    image_color_left_frame_id: "color_camera_left"
    image_color_right_frame_id: "color_camera_right"
    imu_frame_id: "imu"
    nav_sat_frame_id: "oxts"
    marker_arr_frame_id: "oxts"

    publish_rate: 10